"""add skill_executions table

Revision ID: 7aad7f89fd81
Revises: bb2994dcdc17
Create Date: 2026-06-20 17:30:58.781668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aad7f89fd81'
down_revision: Union[str, Sequence[str], None] = 'bb2994dcdc17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_executions_created_at'), 'skill_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_skill_executions_skill_name'), 'skill_executions', ['skill_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_executions_skill_name'), table_name='skill_executions')
    op.drop_index(op.f('ix_skill_executions_created_at'), table_name='skill_executions')
    op.drop_table('skill_executions')
    # ### end Alembic commands ###
