"""initial schema: pipeline, leads, vault, memory, constitution

Revision ID: 92cc648701e0
Revises: 
Create Date: 2026-06-20 01:24:24.820286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '92cc648701e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constitution_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index(op.f('ix_constitution_versions_active'), 'constitution_versions', ['active'], unique=False)
    op.create_table('episodic_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodic_memories_agent_id'), 'episodic_memories', ['agent_id'], unique=False)
    op.create_index(op.f('ix_episodic_memories_created_at'), 'episodic_memories', ['created_at'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_SEQUENCE', 'BOOKED', 'CLOSED', 'LOST', name='leadstatus'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('buying_stage', sa.Enum('AWARENESS', 'CONSIDERATION', 'DECISION', 'NEGOTIATION', name='buyingstage'), nullable=True),
    sa.Column('icp_score', sa.Float(), nullable=True),
    sa.Column('touchpoints', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_type', sa.Enum('CEO', 'CMO', 'RESEARCH', 'SDR', 'AE', 'ANALYST', 'EMAIL', 'RISK', name='agenttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SCHEDULED', 'POSTED', 'VETOED', name='pipelinestatus'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('alternatives_considered', sa.JSON(), nullable=True),
    sa.Column('approval_tier', sa.String(length=30), nullable=True),
    sa.Column('debate_log', sa.JSON(), nullable=True),
    sa.Column('constitution_violations', sa.JSON(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflection_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('task_context', sa.String(length=300), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflection_memories_agent_id'), 'reflection_memories', ['agent_id'], unique=False)
    op.create_index(op.f('ix_reflection_memories_created_at'), 'reflection_memories', ['created_at'], unique=False)
    op.create_table('vault_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_documents_collection'), 'vault_documents', ['collection'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_documents_collection'), table_name='vault_documents')
    op.drop_table('vault_documents')
    op.drop_index(op.f('ix_reflection_memories_created_at'), table_name='reflection_memories')
    op.drop_index(op.f('ix_reflection_memories_agent_id'), table_name='reflection_memories')
    op.drop_table('reflection_memories')
    op.drop_table('pipeline_items')
    op.drop_table('leads')
    op.drop_index(op.f('ix_episodic_memories_created_at'), table_name='episodic_memories')
    op.drop_index(op.f('ix_episodic_memories_agent_id'), table_name='episodic_memories')
    op.drop_table('episodic_memories')
    op.drop_index(op.f('ix_constitution_versions_active'), table_name='constitution_versions')
    op.drop_table('constitution_versions')
    # ### end Alembic commands ###
