"""add run_id to evaluations, add agent_run_errors table

Revision ID: bb2994dcdc17
Revises: fe251a95e87a
Create Date: 2026-06-20 16:12:02.910664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2994dcdc17'
down_revision: Union[str, Sequence[str], None] = 'fe251a95e87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run_errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_errors_agent_id'), 'agent_run_errors', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_run_errors_created_at'), 'agent_run_errors', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_run_errors_run_id'), 'agent_run_errors', ['run_id'], unique=False)
    op.add_column('evaluations', sa.Column('run_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_evaluations_run_id'), 'evaluations', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_run_id'), table_name='evaluations')
    op.drop_column('evaluations', 'run_id')
    op.drop_index(op.f('ix_agent_run_errors_run_id'), table_name='agent_run_errors')
    op.drop_index(op.f('ix_agent_run_errors_created_at'), table_name='agent_run_errors')
    op.drop_index(op.f('ix_agent_run_errors_agent_id'), table_name='agent_run_errors')
    op.drop_table('agent_run_errors')
    # ### end Alembic commands ###
