"""add heuristic_versions table

Revision ID: fe251a95e87a
Revises: dd8282b1d9b9
Create Date: 2026-06-20 15:31:23.484860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe251a95e87a'
down_revision: Union[str, Sequence[str], None] = 'dd8282b1d9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heuristic_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index(op.f('ix_heuristic_versions_active'), 'heuristic_versions', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heuristic_versions_active'), table_name='heuristic_versions')
    op.drop_table('heuristic_versions')
    # ### end Alembic commands ###
