'use client';
import { useEffect, useState } from 'react';
import { useSureflowStore } from '@/lib/store';
import type { PipelineItem, PipelineStatus } from '@/types';
import { CheckCircle, XCircle, Calendar, ExternalLink, Send } from 'lucide-react';

function ContentModal({ item, onClose }: { item: PipelineItem | null; onClose: () => void }) {
  if (!item) return null;
  
  const publishToMCP = async () => {
    try {
      const res = await fetch(`http://localhost:8000/api/v1/pipeline/items/${item.id}/post`, { method: 'POST' });
      if (res.ok) {
        alert('Published via MCP!');
        onClose();
      } else {
        alert('Publishing failed');
      }
    } catch (e) {
      console.error(e);
      alert('Error publishing');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="glass-card w-full max-w-2xl max-h-[85vh] overflow-y-auto p-6 relative" style={{ background: 'var(--bg-secondary)' }}>
        <button onClick={onClose} className="absolute top-4 right-4 text-gray-400 hover:text-white">✕</button>
        <div className="mb-4">
          <span className={`badge badge-${item.status} mb-2`}>{item.platform}</span>
          <h2 className="text-xl font-bold" style={{ color: 'var(--text-primary)' }}>{item.title}</h2>
          <p className="text-sm mt-1" style={{ color: 'var(--text-muted)' }}>Generated by {item.agent_type} - {item.stage}</p>
        </div>
        
        <div className="mb-6">
          <h3 className="font-semibold mb-2" style={{ color: 'var(--text-primary)' }}>Content</h3>
          <div className="p-4 rounded-lg text-sm whitespace-pre-wrap" style={{ background: 'rgba(255,255,255,0.05)', color: 'var(--text-secondary)' }}>
            {item.content}
          </div>
        </div>

        {item.meta_data && Object.keys(item.meta_data).length > 0 && (
          <div className="mb-6">
            <h3 className="font-semibold mb-2" style={{ color: 'var(--text-primary)' }}>Agent Meta Data</h3>
            <pre className="p-4 rounded-lg text-xs overflow-x-auto" style={{ background: 'rgba(0,0,0,0.2)', color: 'var(--text-muted)' }}>
              {JSON.stringify(item.meta_data, null, 2)}
            </pre>
          </div>
        )}

        <div className="flex justify-end gap-3 mt-6">
          <button onClick={onClose} className="px-4 py-2 rounded-lg text-sm" style={{ background: 'rgba(255,255,255,0.1)' }}>Close</button>
          {item.status === 'approved' && (
            <button onClick={publishToMCP} className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm" style={{ background: 'var(--primary)', color: 'white' }}>
              <Send size={16} /> Publish via MCP
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

const COLUMNS: { key: PipelineStatus; label: string }[] = [
  { key: 'pending',   label: 'Pending Review' },
  { key: 'approved',  label: 'Approved' },
  { key: 'scheduled', label: 'Scheduled' },
  { key: 'posted',    label: 'Posted' },
];

function ContentCard({ item, onApprove, onReject, onClick }: {
  item: PipelineItem;
  onApprove?: () => void;
  onReject?: () => void;
  onClick?: () => void;
}) {
  return (
    <div id={`content-card-${item.id}`} className="glass-card glass-card-hover p-4 mb-3 cursor-pointer" onClick={onClick}>
      <div className="flex items-center gap-2 mb-2">
        <span className={`badge badge-${item.status}`}>{item.platform}</span>
        <span className="text-xs" style={{ color: 'var(--text-muted)' }}>{item.stage}</span>
      </div>
      <p className="text-sm font-medium mb-2 leading-snug" style={{ color: 'var(--text-primary)' }}>
        {item.title}
      </p>
      <p className="text-xs line-clamp-3 mb-3" style={{ color: 'var(--text-secondary)' }}>
        {item.content}
      </p>
      <div className="flex items-center justify-between">
        <span className="text-xs font-mono" style={{ color: 'var(--text-muted)' }}>
          {item.agent_type}
        </span>
        {item.status === 'pending' && (
          <div className="flex gap-1.5">
            <button
              id={`card-approve-${item.id}`}
              onClick={(e) => { e.stopPropagation(); onApprove?.(); }}
              className="flex items-center gap-1 px-2 py-1 rounded-lg text-xs"
              style={{ background: 'rgba(16,185,129,0.1)', color: '#10b981' }}
            >
              <CheckCircle size={10} /> OK
            </button>
            <button
              id={`card-reject-${item.id}`}
              onClick={(e) => { e.stopPropagation(); onReject?.(); }}
              className="flex items-center gap-1 px-2 py-1 rounded-lg text-xs"
              style={{ background: 'rgba(239,68,68,0.1)', color: '#ef4444' }}
            >
              <XCircle size={10} /> ✕
            </button>
          </div>
        )}
        {item.status === 'approved' && (
          <button
            id={`schedule-${item.id}`}
            onClick={(e) => e.stopPropagation()}
            className="flex items-center gap-1 px-2 py-1 rounded-lg text-xs"
            style={{ background: 'rgba(99,102,241,0.1)', color: '#818cf8' }}
          >
            <Calendar size={10} /> Schedule
          </button>
        )}
      </div>
    </div>
  );
}

export default function ContentPipeline() {
  const { pipelineItems, fetchPipelineItems, updateItemStatus } = useSureflowStore();
  const [selectedItem, setSelectedItem] = useState<PipelineItem | null>(null);

  useEffect(() => { fetchPipelineItems(); }, [fetchPipelineItems]);

  const byStatus = (status: PipelineStatus) => pipelineItems.filter(i => i.status === status);

  return (
    <div className="p-8 min-h-screen" style={{ background: 'var(--bg-primary)' }}>
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-1" style={{ color: 'var(--text-primary)' }}>
          Content <span className="gradient-text">Pipeline</span>
        </h1>
        <p style={{ color: 'var(--text-secondary)' }}>Review, approve, and schedule AI-generated SaaS & FinTech engagement content based on social media trends</p>
      </div>

      <div className="flex gap-5 overflow-x-auto pb-4" style={{ minHeight: '60vh' }}>
        {COLUMNS.map(col => {
          const items = byStatus(col.key);
          return (
            <div key={col.key} className="kanban-col flex-shrink-0" style={{ width: 300 }}>
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-semibold text-sm" style={{ color: 'var(--text-primary)' }}>
                  {col.label}
                </h3>
                <span
                  className="text-xs font-bold px-2 py-0.5 rounded-full"
                  style={{ background: 'rgba(255,255,255,0.06)', color: 'var(--text-muted)' }}
                >
                  {items.length}
                </span>
              </div>
              <div>
                {items.length === 0 ? (
                  <div className="text-center py-8 text-xs" style={{ color: 'var(--text-muted)' }}>
                    No items
                  </div>
                ) : (
                  items.map(item => (
                    <ContentCard
                      key={item.id}
                      item={item}
                      onApprove={() => updateItemStatus(item.id, 'approved')}
                      onReject={() => updateItemStatus(item.id, 'rejected')}
                      onClick={() => setSelectedItem(item)}
                    />
                  ))
                )}
              </div>
            </div>
          );
        })}
      </div>
      <ContentModal item={selectedItem} onClose={() => setSelectedItem(null)} />
    </div>
  );
}
